name: Build and Publish

on:
  push:
    branches: [ '**' ]

jobs:
  check:
    name: Lint and Test
    runs-on: [ubuntu-latest, self-hosted]     
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 29
          build-tools: 31.0.0
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Run checks
        run: |
          ./gradlew --no-daemon clean
          ./gradlew --no-daemon --parallel \
            :lib-extractor:check \
            :lib-exoplayer:check \
            :lib-exoplayer-hls:check \
            :lib-ui:check \
            :demo:testNoDecoderExtensionsDebugUnitTest
            
      - name: Publish unit test results (JUnit)
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            **/build/test-results/test*/TEST-*.xml
            **/buildout/test-results/test*/TEST-*.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/build/test-results/test*/TEST-*.xml
            **/buildout/test-results/test*/TEST-*.xml
            **/build/reports/tests/**/*.html
            **/buildout/reports/tests/**/*.html
          retention-days: 15
      
      - name: Upload lint results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: |
            **/build/reports/lint-results*.xml
            **/build/reports/lint-results*.html
          retention-days: 15
